"""Configuration and shared type definitions for the Amelia orchestrator.

Contains type aliases (DriverType, TrackerType) and
Pydantic models (RetryConfig, Profile, Settings, Issue) used throughout
the Amelia agentic coding orchestrator.
"""
from pathlib import Path
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


DriverType = Literal["cli:claude", "api:openrouter", "cli", "api"]
TrackerType = Literal["jira", "github", "none", "noop"]


class RetryConfig(BaseModel):
    """Retry configuration for transient failures.

    Attributes:
        max_retries: Maximum number of retry attempts (0-10).
        base_delay: Base delay in seconds for exponential backoff (0.1-30.0).
        max_delay: Maximum delay cap in seconds (1.0-300.0).
    """

    max_retries: int = Field(
        default=3, ge=0, le=10, description="Maximum number of retry attempts"
    )
    base_delay: float = Field(
        default=1.0, ge=0.1, le=30.0, description="Base delay in seconds for exponential backoff"
    )
    max_delay: float = Field(
        default=60.0, ge=1.0, le=300.0, description="Maximum delay cap in seconds"
    )


class Profile(BaseModel):
    """Configuration profile for Amelia execution.

    This model is frozen (immutable) to support the stateless reducer pattern.
    Use model_copy(update={...}) to create modified copies.

    Attributes:
        name: Profile name (e.g., 'work', 'personal').
        driver: LLM driver type (e.g., 'api:openrouter', 'cli:claude').
        model: LLM model identifier. For cli:claude use 'sonnet', 'opus', or 'haiku'.
            For api:openrouter use model name directly (e.g., 'minimax/minimax-m2').
            The provider is inferred from the driver setting.
        tracker: Issue tracker type (jira, github, none, noop).
        working_dir: Working directory for agentic execution.
        plan_output_dir: Directory for saving implementation plans (default: docs/plans).
        plan_path_pattern: Path pattern for plan files with {date} and {issue_key} placeholders.
        retry: Retry configuration for transient failures.
        max_review_iterations: Maximum review-fix loop iterations before terminating.
        auto_approve_reviews: Skip human approval steps in review workflow.
    """

    model_config = ConfigDict(frozen=True)

    name: str
    driver: DriverType
    model: str
    tracker: TrackerType = "none"
    working_dir: str
    plan_output_dir: str = "docs/plans"
    plan_path_pattern: str = "docs/plans/{date}-{issue_key}.md"
    validator_model: str
    """Model for plan validation. Uses a fast/cheap model for extraction."""
    retry: RetryConfig = Field(default_factory=RetryConfig)
    max_review_iterations: int = 3
    max_task_review_iterations: int = 5  # Per-task review iteration limit (for task-based execution)
    auto_approve_reviews: bool = False

class Settings(BaseModel):
    """Global settings for Amelia.

    Attributes:
        active_profile: Name of the currently active profile.
        profiles: Dictionary mapping profile names to Profile objects.
    """
    active_profile: str
    profiles: dict[str, Profile]

class Issue(BaseModel):
    """Issue or ticket to be worked on.

    Attributes:
        id: Unique issue identifier (e.g., 'JIRA-123', 'GH-456').
        title: Issue title or summary.
        description: Detailed issue description.
        status: Current issue status (default: 'open').
    """
    id: str
    title: str
    description: str
    status: str = "open"


class Design(BaseModel):
    """Design document for implementation.

    Can be user-provided via import or generated by a future Brainstorming pipeline.

    Attributes:
        content: The markdown content of the design document.
        source: Where the design came from ("import", "brainstorming", "file").
    """

    content: str
    source: str = "import"

    @classmethod
    def from_file(cls, path: Path | str) -> "Design":
        """Load design from markdown file."""
        content = Path(path).read_text(encoding="utf-8")
        return cls(content=content, source="file")


Severity = Literal["low", "medium", "high", "critical"]


class ReviewResult(BaseModel):
    """Result from a code review.

    Attributes:
        reviewer_persona: The persona or role of the reviewer.
        approved: Whether the review approved the changes.
        comments: List of actionable issues to fix. Filtered at creation time
            to exclude positive observations.
        severity: Severity level of issues found (low, medium, high, critical).
    """

    model_config = ConfigDict(frozen=True)

    reviewer_persona: str
    approved: bool
    comments: list[str]
    severity: Severity
