/**
 * Token usage and cost types.
 * Mirrors the Python Pydantic models in `amelia/server/models/tokens.py`.
 */

/**
 * Detailed token usage information for a single LLM request.
 * Tracks input, output, and cache tokens separately for cost analysis.
 */
export interface TokenUsage {
  /** Unique identifier for this token usage record. */
  id: string;

  /** ID of the workflow this usage belongs to. */
  workflow_id: string;

  /**
   * Name of the agent that made this request.
   *
   * Open string to match the backend (`TokenUsage.agent: str`). Token usage is
   * recorded for many agents — `architect`, `developer`, `reviewer`,
   * `task_reviewer`, `evaluator`, `classifier` — so this is intentionally not a
   * closed union.
   */
  agent: string;

  /** Name of the LLM model used (e.g., 'claude-sonnet-4-5', 'gpt-4'). */
  model: string;

  /** Number of input tokens sent to the model. */
  input_tokens: number;

  /** Number of output tokens generated by the model. */
  output_tokens: number;

  /** Number of tokens read from the prompt cache (not billed at full rate). */
  cache_read_tokens: number;

  /** Number of tokens written to the prompt cache. */
  cache_creation_tokens: number;

  /** Calculated cost in USD for this request. */
  cost_usd: number;

  /** Duration of the request in milliseconds. */
  duration_ms: number;

  /** Number of turns (conversation exchanges) in this request. */
  num_turns: number;

  /** ISO 8601 timestamp when this request was made. */
  timestamp: string;
}

/**
 * Aggregated token usage and cost for a workflow.
 * Provides a high-level summary with per-agent breakdown.
 */
export interface TokenSummary {
  /** Total number of input tokens across all requests. */
  total_input_tokens: number;

  /** Total number of output tokens across all requests. */
  total_output_tokens: number;

  /** Total number of cache read tokens across all requests. */
  total_cache_read_tokens: number;

  /** Total cost in USD for all token usage. */
  total_cost_usd: number;

  /** Total duration in milliseconds across all requests. */
  total_duration_ms: number;

  /** Total number of turns across all requests. */
  total_turns: number;

  /** Detailed breakdown of token usage by agent. */
  breakdown: TokenUsage[];
}
