"""Type stubs for deepagents.backends.protocol module."""

import abc
from dataclasses import dataclass
from typing import Any, Literal, NotRequired

from typing_extensions import TypedDict

FileOperationError = Literal[
    "file_not_found",
    "permission_denied",
    "is_directory",
    "invalid_path",
]

@dataclass
class FileDownloadResponse:
    path: str
    content: bytes | None = ...
    error: FileOperationError | None = ...

@dataclass
class FileUploadResponse:
    path: str
    error: FileOperationError | None = ...

class FileInfo(TypedDict):
    path: str
    is_dir: NotRequired[bool]
    size: NotRequired[int]
    modified_at: NotRequired[str]

class GrepMatch(TypedDict):
    path: str
    line: int
    text: str

@dataclass
class WriteResult:
    error: str | None = ...
    path: str | None = ...
    files_update: dict[str, Any] | None = ...

@dataclass
class EditResult:
    error: str | None = ...
    path: str | None = ...
    files_update: dict[str, Any] | None = ...
    occurrences: int | None = ...

@dataclass
class ExecuteResponse:
    output: str
    exit_code: int | None = ...
    truncated: bool = ...

class BackendProtocol(abc.ABC):
    """Protocol for pluggable memory backends."""

    def ls_info(self, path: str) -> list[FileInfo]: ...
    async def als_info(self, path: str) -> list[FileInfo]: ...
    def read(self, file_path: str, offset: int = ..., limit: int = ...) -> str: ...
    async def aread(self, file_path: str, offset: int = ..., limit: int = ...) -> str: ...
    def grep_raw(
        self, pattern: str, path: str | None = ..., glob: str | None = ...
    ) -> list[GrepMatch] | str: ...
    async def agrep_raw(
        self, pattern: str, path: str | None = ..., glob: str | None = ...
    ) -> list[GrepMatch] | str: ...
    def glob_info(self, pattern: str, path: str = ...) -> list[FileInfo]: ...
    async def aglob_info(self, pattern: str, path: str = ...) -> list[FileInfo]: ...
    def write(self, file_path: str, content: str) -> WriteResult: ...
    async def awrite(self, file_path: str, content: str) -> WriteResult: ...
    def edit(
        self, file_path: str, old_string: str, new_string: str, replace_all: bool = ...
    ) -> EditResult: ...
    async def aedit(
        self, file_path: str, old_string: str, new_string: str, replace_all: bool = ...
    ) -> EditResult: ...
    def upload_files(self, files: list[tuple[str, bytes]]) -> list[FileUploadResponse]: ...
    async def aupload_files(
        self, files: list[tuple[str, bytes]]
    ) -> list[FileUploadResponse]: ...
    def download_files(self, paths: list[str]) -> list[FileDownloadResponse]: ...
    async def adownload_files(self, paths: list[str]) -> list[FileDownloadResponse]: ...

class SandboxBackendProtocol(BackendProtocol):
    """Protocol for sandboxed backends with isolated runtime."""

    def execute(self, command: str) -> ExecuteResponse: ...
    async def aexecute(self, command: str) -> ExecuteResponse: ...
    @property
    def id(self) -> str: ...
